### ISSUE TITLE
この形になった理由は？

### ISSUE THREAD

**Issue by C0B21048** [c0b2105481/ProjExD_pub#6]
ランダムを使う方法の中でもいろいろなものがありますが、どうしてこの形を採用したのですか？

https://github.com/c0b2105481/ProjExD_pub/blob/396a823622aeb0e58008bc8938fb22e1eac70d37/Rex.py#L121

**Comment by c0b2105481** [comment]
プログラムを書く上で一番実装がしやすい形だからです
